### ISSUE TITLE
python module issue

### ISSUE THREAD

**Issue by tushar-ahmed** [boxiangliu/covseq#3]
Hello I'm facing issues using your library

Traceback (most recent call last):
  File "annotation/annotation.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'

But I have click installed on my laptop. Later I installed click in conda environment  and tried from that environment. but facing the same problem

click-7.1.2 is installed 

Thank you in advance

**Comment by tushar-ahmed** [comment]
I have sorted it out.

sorry for inconveniences

**Comment by smruti241** [comment]
Tushar, i am facing some python issues while running this covseq. Can you please help me?
Traceback (most recent call last):
  File "/home/smrutip/smruti_project/gisaid_project/covseq/annotation/annotation.py", line 10, in <module>
    from vcf.fasta2vcf import fasta2vcf
  File "/home/smrutip/smruti_project/gisaid_project/covseq/./vcf/fasta2vcf.py", line 8, in <module>
    from utils import DefaultOrderedDict
  File "/home/smrutip/smruti_project/gisaid_project/covseq/./utils.py", line 3, in <module>
    from collections import OrderedDict, Callable
ImportError: cannot import name 'Callable' from 'collections' (/home/smrutip/anaconda3/envs/covid_project/lib/python3.10/collections/__init__.py)

Why this package is not called, can you please let me know?

**Comment by tushar-ahmed** [comment]
@smruti241 Did you try changing the python version?
