### ISSUE TITLE
GISAID sequences preprocess issue 

### ISSUE THREAD

**Issue by tushar-ahmed** [boxiangliu/covseq#4]
(base) d3w@d3w:~/covseq$ python3 preprocess/concatenate_fasta.py -i TRIAL/ -o TRIAL/test.fasta --gisaid_metadata gisaid_hcov19.xls 
#########################
# Concatenate all FASTA #
#########################
Input: TRIAL/
Output: TRIAL/test.fasta
Traceback (most recent call last):
  File "preprocess/concatenate_fasta.py", line 79, in <module>
    main()
  File "/home/d3w/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/d3w/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/d3w/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/d3w/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "preprocess/concatenate_fasta.py", line 74, in main
    cngb_id_map = get_cngb_id_map(cgnb_metadata)
  File "preprocess/concatenate_fasta.py", line 11, in get_cngb_id_map
    with open(in_fn) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

I am facing this issue. help please

NB: I have installed python dependencies in conda environment.

**Comment by milw** [comment]
apparently you need to specify **both** --cngb_metadata <path> and --gisaid_metadata <path>
